// Generated Agent Skills must be deterministic, spec-conformant, and derived
// from the canonical guide topics.

import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";

import { buildSkillFiles, SKILL_TARGETS } from "../src/skills.mjs";
import { skillCommand } from "../src/commands/skill.mjs";
import { GUIDE_TOPICS } from "../src/commands/guide.mjs";
import { readGuide } from "../src/runtime.mjs";

test("skill files are generated for every target and topic", async () => {
  for (const target of Object.keys(SKILL_TARGETS)) {
    const files = await buildSkillFiles(target);
    assert.ok(files.has("SKILL.md"));
    for (const topic of GUIDE_TOPICS) {
      assert.ok(files.has(`references/${topic}.md`), `${target} is missing ${topic}`);
    }
  }
});

test("SKILL.md follows the Agent Skills front matter specification", async () => {
  const files = await buildSkillFiles("codex");
  const skill = files.get("SKILL.md");
  const match = /^---\n([\s\S]*?)\n---\n/.exec(skill);
  assert.ok(match, "SKILL.md must start with YAML front matter");
  assert.match(match[1], /^name: "markdstage"$/m);
  assert.match(match[1], /^description: "/m);
  const description = JSON.parse(/^description: (".*")$/m.exec(match[1])[1]);
  assert.ok(description.length <= 1024);
  assert.match(skill, /# MarkdStage/);
});

test("reference files come from the canonical guide", async () => {
  const files = await buildSkillFiles("claude");
  const guide = (await readGuide("architecture-dsl")).trim();
  const reference = files.get("references/architecture-dsl.md");
  assert.ok(reference.includes(guide));
  assert.match(reference, /Generated by `markdstage skill install`/);
});

test("only the Copilot skill mentions the canvas adapter", async () => {
  const copilot = (await buildSkillFiles("copilot")).get("SKILL.md");
  const codex = (await buildSkillFiles("codex")).get("SKILL.md");
  assert.match(copilot, /## Canvas adapter/);
  assert.doesNotMatch(codex, /## Canvas adapter/);
});

test("generated skills explain watch-mode Architecture editing", async () => {
  const skill = (await buildSkillFiles("codex")).get("SKILL.md");
  assert.match(skill, /present --watch/);
  assert.match(skill, /starts in viewing mode/);
  assert.match(skill, /detailed designer/);
  assert.match(skill, /without\s+`--watch`\s+is read-only/);
});

test("generated skills teach the diagnostic-first authoring loop", async () => {
  const skill = (await buildSkillFiles("codex")).get("SKILL.md");
  const stages = [
    "markdstage guide slide-format",
    "markdstage validate slides.md --json",
    "markdstage present slides.md --watch",
    "markdstage inspect slides.md --json",
    "markdstage capture slides.md",
    "markdstage presentation slides.md",
    "markdstage export slides.md --output slides.pdf",
    "markdstage export slides.md --output slides.pptx",
  ];
  let previous = -1;
  for (const stage of stages) {
    const index = skill.indexOf(stage);
    assert.ok(index > previous, `${stage} must appear in workflow order`);
    previous = index;
  }
  assert.match(skill, /captures only clipped slides/);
  assert.match(skill, /Prefer structured validation\s+and layout diagnostics over capturing every slide/);
});

test("generation is deterministic", async () => {
  const first = await buildSkillFiles("codex");
  const second = await buildSkillFiles("codex");
  assert.deepEqual([...first.entries()], [...second.entries()]);
});

test("install does not overwrite user-modified files without --force", async () => {
  const dir = await mkdtemp(join(tmpdir(), "markdstage-skill-"));
  try {
    await skillCommand({ action: "install", target: "codex", root: dir });
    const skillFile = join(dir, ...SKILL_TARGETS.codex.directory, "SKILL.md");
    await writeFile(skillFile, "# edited by the user\n", "utf8");

    const report = await skillCommand({ action: "install", target: "codex", root: dir });
    assert.equal(report.conflicts, 1);
    assert.equal(await readFile(skillFile, "utf8"), "# edited by the user\n");

    const forced = await skillCommand({
      action: "install",
      target: "codex",
      root: dir,
      force: true,
    });
    assert.equal(forced.conflicts, 0);
    assert.notEqual(await readFile(skillFile, "utf8"), "# edited by the user\n");
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("check never writes files", async () => {
  const dir = await mkdtemp(join(tmpdir(), "markdstage-skill-check-"));
  try {
    const report = await skillCommand({ action: "check", target: "claude", root: dir });
    assert.ok(report.changed > 0);
    await assert.rejects(
      readFile(join(dir, ...SKILL_TARGETS.claude.directory, "SKILL.md"), "utf8"),
    );
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("unknown targets and actions are rejected", async () => {
  await assert.rejects(skillCommand({ target: "emacs" }), /Unknown skill target/);
  await assert.rejects(skillCommand({ action: "remove" }), /Unknown skill action/);
});

test("the repository skills are in sync with the guide", async () => {
  const repoRoot = fileURLToPath(new URL("../../../", import.meta.url));
  const report = await skillCommand({
    action: "check",
    target: "codex,claude",
    root: repoRoot,
  });
  assert.equal(
    report.changed,
    0,
    "Run `npm run skills` from the repository root and commit the result.",
  );
});
